{
 "title": "Device Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Device Overview",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(arch,'no_data') as 'Architecture',\nifnull(productmodel,'nodata') as 'Productmodel',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY arch,productmodel\n"
    }
   ]
  },
  {
   "title": "Daily Restart Count",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n(SELECT count(reboot) FROM ATVstats where reboot='restart' and timestamp > cast(current_timestamp as date)) as 'Game Restarts',\n(SELECT count(reboot) FROM ATVstats where reboot='reboot' and timestamp > cast(current_timestamp as date)) as 'Device Reboots'"
    }
   ]
  },
  {
   "title": "App Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(pogo,'no_data') as 'PoGo',\nifnull(atlas,'no_data') as 'Atlas',\nifnull(magisk,'no_data') as 'Magisk',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY pogo, atlas, magisk\n"
    }
   ]
  },
  {
   "title": "Atlas settings",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(rdmUrl, 'no_data') as 'rdmUrl',\nifnull(authBearer, 'no_data') as 'authBearer',\nifnull(token, 'no_data') as 'deviceAuthToken',\nifnull(email, 'no_data') as 'email',\nifnull(onBoot, 'no_data') as 'runOnBoot',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY rdmUrl,authBearer,token,email,onBoot"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\nmin(temperature) as 'minTemp',\navg(temperature) as 'avgTemp',\nmax(temperature) as 'maxTemp'\nfrom ATVsummary\nwhere timestamp > cast(current_timestamp as date)"
    }
   ]
  },
  {
   "title": "Temperature (Bottom 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > cast(current_timestamp as date)\norder by temperature ASC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Temperature (Top 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - cast(current_timestamp as date)\norder by temperature DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Average Jump",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\nmin(avj) as 'minAvj',\navg(avj) as 'avgAvj',\nmax(avj) as 'maxAvj'\nfrom ATVstats\nwhere timestamp > now()-interval 20 minute"
    }
   ]
  },
  {
   "title": "Average Jump (Bottom 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT deviceName, min(avj)\nFROM ATVstats\nwhere timestamp > now() - interval 20 minute\nGroup by deviceName\norder by min(avj) ASC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Average Jump (Top 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT deviceName, max(avj)\nFROM ATVstats\nwhere timestamp >  now() - interval 20 minute\nGroup by deviceName\norder by max(avj) DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Current Jump",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\nmin(cur) as 'minCur',\navg(cur) as 'avgCur',\nmax(cur) as 'maxCur'\nfrom ATVstats\nwhere timestamp > now() - interval 1 hour"
    }
   ]
  },
  {
   "title": "Current Jump (Bottom 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT deviceName, min(cur)\nFROM ATVstats\nwhere timestamp > now() -  interval 1 hour\nGroup by deviceName\norder by min(cur) ASC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Current Jump (Top 5)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT deviceName, max(cur)\nFROM ATVstats\nwhere timestamp > now() -  interval 1 hour\nGroup by deviceName\norder by max(cur) DESC\nlimit 5\n"
    }
   ]
  }
 ]
}