{
 "title": "Performance Trends",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ATV",
    "label": "ATV",
    "query": "SELECT DISTINCT(deviceName) FROM ATVstats;"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Pogo Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuPogoPct AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU AtasUsage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuApct AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Load 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuL5 AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Load 10min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuL10 AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Load 15min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuL15 AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "ATV Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ATV Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  temperature AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "Average Jump",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  avj AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp)\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MemFree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  memFree AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "MemUsage Pogo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  memPogo AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "MemUsage Atlas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  memAtlas AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  }
 ]
}